<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.techsenger.ceffx</groupId>
        <artifactId>ceffx</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>com.techsenger.ceffx</groupId>
    <artifactId>ceffx-demo</artifactId>
    <packaging>jar</packaging>
    <name>CEFFX - Demo</name>
    <description>Demo application</description>

    <profiles>
        <profile>
            <id>natives-linux</id>
            <activation>
                <os>
                    <name>Linux</name>
                </os>
            </activation>
            <properties>
                <natives.classifier>linux</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>natives-mac</id>
            <activation>
                <os>
                    <name>Mac OS X</name>
                    <arch>x86_64</arch>
                </os>
            </activation>
            <properties>
                <natives.classifier>mac</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>natives-mac-aarch64</id>
            <activation>
                <os>
                    <name>Mac OS X</name>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <properties>
                <natives.classifier>mac-aarch64</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>natives-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <natives.classifier>win</natives.classifier>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>com.techsenger.ceffx</groupId>
            <artifactId>ceffx-natives</artifactId>
            <classifier>${natives.classifier}</classifier>
        </dependency>
        <dependency>
            <groupId>com.techsenger.ceffx</groupId>
            <artifactId>ceffx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.mkpaz</groupId>
            <artifactId>atlantafx-base</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.patternfx</groupId>
            <artifactId>patternfx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.patternfx</groupId>
            <artifactId>patternfx-mvp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-material</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-icons</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-layout</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-dialogs</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.shellfx</groupId>
            <artifactId>shellfx-devtools</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.tabpanepro</groupId>
            <artifactId>tabpanepro-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.techsenger.toolkit</groupId>
            <artifactId>toolkit-fx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
        <dependency>
            <!-- ico plugin for ImageIO -->
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-bmp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- $ mvn javafx:run -->
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>${javafx.plugin.version}</version>
                <configuration>
                    <mainClass>com.techsenger.ceffx.demo.Demo</mainClass>
                    <options>
                        <option>-Xrunjdwp:transport=dt_socket,address=7700,server=y,suspend=n</option>
                        <option>-Dceffx.natives.path=${project.build.directory}/natives</option>
                        <option>-Djava.library.path=${project.build.directory}/natives${path.separator}${project.build.directory}/natives/Lib</option>
                        <option>--enable-native-access=javafx.graphics</option>
                        <option>--enable-native-access=com.techsenger.ceffx.core</option>
                        <option>-Djavafx.enablePreview=true</option>
                        <option>-Dlog4j.configurationFile=src/main/resources/log4j2.xml</option>
                    </options>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
